name: animation2
version: 0.6.01
authors:
  - Kai Sellgren <kaisellgren@gmail.com>
  - Stefan Ladage <stefan@dreamlogics.com>
description: Animate HTML elements similar to jQuery's animate(). (Ported to Dart 2)
homepage: https://github.com/DreamLogics/Animation
environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  build_runner: ^1.7.3
  build_test: ^0.10.11
  build_web_compilers: ^2.7.2
  test: ^1.9.4

