name: animation
version: 0.5.21
description: Animate HTML elements similar to jQuery's animate().
author: Kai Sellgren <kaisellgren@gmail.com>
homepage: http://github.com/kaisellgren/Animation
dependencies:
  browser: '>=0.9.0 < 0.10.0'
dev_dependencies:  
  unittest: '>=0.9.0 < 0.10.0'
