name: animation
version: 0.1.0
description: Animate elements.
author: Kai Sellgren <kaisellgren@gmail.com>
homepage: http://github.com/kaisellgren/Animation
dependencies:
  unittest:
    sdk: unittest