name: animation
version: 0.2.5
description: Animate HTML elements.
author: Kai Sellgren <kaisellgren@gmail.com>
homepage: http://github.com/kaisellgren/Animation
dependencies:
  unittest: any
  browser: ">=0.3.1+1 <0.3.2"